# See https://github.com/helm/chart-testing#configuration
remote: origin
target-branch: main
chart-dirs:
  - charts
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - bjw-s=http://bjw-s.github.io/helm-charts/
  - truecharts-library=https://library-charts.truecharts.org/
helm-extra-args: --timeout 600s
excluded-charts:
  - graphite-exporter
  - maian-music
  - owncloud
  - smtp-relay
  - dbdump
  - autonodelabel
  - openssh-server
  - connectbox-exporter
  - liturgical-colour
  - lldap
